[package]
name = "localssl-rs"
version = "0.1.0"
authors = ["Subroto <subroto.biswas@upgrad.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openssl-sys = "0.9"
openssl = { version = "0.10" }
